# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b337855e9275e957fc5745fec2fd5db8f737c231b2869018cb07dda8c0d080f69d0ebd1675ed95ca60bfd65d283ba9dd711018ba9195220062cfdd0d78c80fe9

test:
  secret_key_base: 043fa3abed23956555f02b6c3c96a779b81076bbfd957b7de1dded89910e36140c32b57e7abe126732637fc4f3c00fb89b4e89b3d8bc0c01ba79ad9c4c344cae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
